spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/epp_db
    username: epp_user
    password: password123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Hibernate crea/actualiza las tablas
    show-sql: true
    properties:
      hibernate:
        default_schema: epp  # Usar esquema epp
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  sql:
    init:
      mode: always  # Ejecuta init.sql para datos iniciales

jwt:
  secret: dev-secret-key-change-in-production-must-be-at-least-256-bits-long-for-hs256
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    root: INFO
    pe.edu.upeu.epp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: on_param

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method